language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-tim-standard' ]; then cd .. && eval "mv $currentfolder generator-tim-standard" && cd generator-tim-standard; fi

